version: '3.8'

services:
  docscrub:
    build:
      context: .
      dockerfile: Dockerfile
    image: docscrub:latest
    container_name: docscrub-app
    ports:
      - "8080:80"
    restart: unless-stopped
    # If you need environment variables, add them here
    # environment:
    #   - NODE_ENV=production
    networks:
      - docscrub-network

networks:
  docscrub-network:
    driver: bridge
